### ISSUE TITLE
to do

### ISSUE THREAD

**Issue by nataliaheliova** [nataliaheliova/Diplomovka#1]
pozn:

- sledovanie bunky by asi malo byt povolene, iba ak nie je aktivovana moznost "Show near nodes only"

- takisto pri coloringOption == original color je combo box zle naplneny

**Comment by RobertSpir** [comment]
ten antialiasing kludne mozete nechat nakoniec, predtym to tam bolo preto, lebo implementacia bola trivialna, neviem ci v DX11 je to take jednoduche

**Comment by nataliaheliova** [comment]
Asi nie je, niekde som sice nasla, ze staci pozmenit nejake nastavenia v tych descriptions, ale nefunguje to...
