### ISSUE TITLE
format textury

### ISSUE THREAD

**Issue by nataliaheliova** [nataliaheliova/Diplomovka#3]
Mam trochu problem s tymi texturami, vyzera to tak, ze je problem len s formatom (subor DataToRender.cs riadok 184).

Povodne sme mali pri texture format L8 - An 8-bit format with luminance only.

Ale comu to odpoveda z tohto: https://msdn.microsoft.com/en-us/library/windows/desktop/bb173059(v=vs.85).aspx  ?

**Comment by RobertSpir** [comment]
ja by som povedal ze DXGI_FORMAT_R8_UINT

**Comment by nataliaheliova** [comment]
S R8_UInt to zostane cele cierne. 

Red channel odpoveda luminance?

**Comment by RobertSpir** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/cc308051%28v=vs.85%29.aspx
malo by to byt ekvivalentne 	DXGI_FORMAT_R8_UNORM 
s poznamkou Use .r swizzle in a shader to duplicate red to other components to get Direct3D 9 behavior.

**Comment by nataliaheliova** [comment]
Dakujem, funguje.
