### ISSUE TITLE
farba uzlov

### ISSUE THREAD

**Issue by nataliaheliova** [nataliaheliova/Diplomovka#4]
Farba uzlov mi okrem custom color nesedi. Povodne sme mali farbu vo Vertexe typu Int32, cize 8 bitov pre kazdy z kanalov RGBA. Lenze teraz shader vyzaduje float4 Color, takze vo Vertexe je farba ulozena ako Color4. 

Na riadkoch 280, 311 a 317 (DataToRender) inicializujem Color4 s pomocou int, ale dostanem uplne inu farbu.

**Comment by RobertSpir** [comment]
mam taky dojem, ze ta float farba by mala byt z rozsahu 0.0-1.0 a  nie 0-255 ako predtym

**Comment by RobertSpir** [comment]
respektive, ak mu davate int, tak to ocakava v poradi ABGR a my mu to davame v ARGB

**Comment by RobertSpir** [comment]
alebo RGBA a my to davame ARGB :D

**Comment by RobertSpir** [comment]
ano, v custom sa dava RGBA
color = new Color4(this.customColor.R, this.customColor.G, this.customColor.B, this.customColor.A);
v tych ostatnych treba zmenit poradie kanalov pri tych bitovych posunoch

**Comment by nataliaheliova** [comment]
takto nejak:  int colour = red << 24 | green << 16 | blue << 8 | 255;

**Comment by RobertSpir** [comment]
hej

**Comment by nataliaheliova** [comment]
Je to pekne, ale je to take do ruzova... Som z tych farieb domotana, vlastne ked som viac poklikala ten custom color, tak ani to nejde vzdy spravne.

**Comment by nataliaheliova** [comment]
Uz to funguje, ale tym ze color vo Vertex je typu Vector4, tak tie buffre maju vyssie naroky na ramku. Mam sa s tym pohrat? Lebo by bolo lepsie pre tu farbu vo vertexe mat int32 ako povodne a tie bitove operacie robit az v shaderi. Lenze ta struktura VS_IN moze obsahovat iba tieto typy zjavne: https://msdn.microsoft.com/en-us/library/windows/desktop/bb509647(v=vs.85).aspx 
To sa mi zda dost velka nevyhoda toho shaderu, ked ma takto obmedzuje... 

Neviem, ci sa tym mam dalej zaoberat alebo nie.

**Comment by RobertSpir** [comment]
o kolko vyssie su tie naroky?

**Comment by nataliaheliova** [comment]
O cca 400MB

**Comment by RobertSpir** [comment]
zatial to neriesme, optimalizacie nechame na koniec...
