### ISSUE TITLE
chybajuce veci

### ISSUE THREAD

**Issue by RobertSpir** [nataliaheliova/Diplomovka#6]
chyba cely projekt ComboCustom
chybaju subory FormChooseDaughter.resx a FormSlices.resx

**Comment by RobertSpir** [comment]
a nebolo by odveci pridat cely folder bin do .gitignore

**Comment by nataliaheliova** [comment]
Lepsie?

**Comment by nataliaheliova** [comment]
Ten opt branch - to bol moj pokus o optimalizaciu. Myslienka bola uchovavat vo Vertex iba poziciu uzlu a do shaderu posielat pole farieb uzlov - cize kazda farba by bola ulozena v pamati jedenkrat pre celu kocku a nie 8krat ako teraz... ale to bolo len tak narychlo a nie moc domyslene, takze to ani poriadne nefunguje... a neskor ma napadlo, ze asi by to bol problem pri trajektoriach, takze to asi ani nebol dobry napad

**Comment by RobertSpir** [comment]
skompilovat mi to sice ide, ale nasledne to padne s
`An unhandled exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll

Additional information: HRESULT: [0x887A002D], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: The application requested an operation that depends on an SDK component that is missing or mismatched.`
niektore sharpdx referencie odkazuju na subory v Grafika3D\bin\Debug\ co nie je uplne najlepsie
Skuste nejak tie referencie opravit a doplnit chybajuce dll tak, aby boli v priecinku s projektom

**Comment by RobertSpir** [comment]
mozno by sa pri tej prilezitosti dalo prejst na sharpdx 3.0...snad sa tam toho vela nezmenilo, ak spravne chapem, tak maximalne bude treba pridat/upravit nejake referencie

**Comment by nataliaheliova** [comment]
Ako je mozne, ze ked si ja stiahnem toto co tu je a spustim, tak mne vsetko ide?

**Comment by RobertSpir** [comment]
neviem, ja asi nemam ten sharpdx nainstalovany cez nuget

**Comment by RobertSpir** [comment]
ok, uz vyzera, ze to ide

**Comment by RobertSpir** [comment]
tak nie, doma mi to stale nejde

**Comment by RobertSpir** [comment]
ok, takze zjavne pri SharpDX.Direct3D11.Device.CreateWithSwapChain(SharpDX.Direct3D.DriverType.Hardware, DeviceCreationFlags.Debug, swapChainDesc, out device, out swapChain); treba mat nainstalovane neviem co, po zmene flags na none to uz ide.
Ale treba povedat, ze bez antialiasingu to vyzera dost skaredo...
